[package]
name = "spi-ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frequency = { git = "ssh://git@github.com/M-Squared-Defence/frequency-rs.git", version = "0.1.0" }
